#!/bin/sh
set -e

dir=/var/pkg/php-modules

cd $dir
apt-get update
apt-get install -y automake \
        bison \
        flex \
        g++ \
        libboost-all-dev \
        libevent-dev \
        libtool \
        pkg-config
cd /tmp \
    && wget http://mirror.bit.edu.cn/apache/thrift/0.10.0/thrift-0.10.0.tar.gz \
    && tar xvf thrift-0.10.0.tar.gz \
    && cd thrift-0.10.0 \
    && ./configure --with-php \
    && make \
    && make install \
    && cd /tmp \
    && rm -rf thrift-0.10.0 thrift-0.10.0.tar.gz